### ISSUE TITLE
merge with original project

### ISSUE THREAD

**Issue by dzienisz** [literalpie/storybook-addon-rtl#14]
Hey, maybe you could contact original maintainer and merge those projects?

**Comment by literalpie** [comment]
Hi, I'm not sure why I would want to do that. They gave me access to the NPM package which is the important thing. It makes sense for the GitHub to be under my account rather than theirs because they are no longer involved. (I was the primary maintainer for some time while it was under their account, but they chose to archive it, which is their choice)
